from __future__ import annotations

from typing import Literal, TypeAlias

# Skill Contract DSL v0.1
#
# This file is the normative API spec for Python Skill Contract blocks.
# A contract block should be written as disciplined Python-shaped code that imports:
#
#     from skill_contract import *
#
# The DSL describes agent behavior. It is not a general-purpose programming
# interface, and agents must not invent functions that are absent from this
# file.
#
# Natural language is allowed inside string and f-string fields. Use call_*()
# markers inside those strings to annotate script, tool, MCP, skill, or human
# interactions.
# These markers do not execute anything; they make the intended call auditable.
# They do not replace structured control-flow gates such as ask_when_missing,
# ask_user, required_when, mode-level inputs/outputs, or
# failure_policy="ask_user".
#
# Minimal complete contract:
# - exactly one skill(...)
# - at least one activate_when(...)
# - do_not_activate_when(...) unless the skill has no meaningful neighbor
# - top-level inputs(...) and outputs(...), or mode-level inputs/outputs on
#   every mode when modes(...) is the behavior surface
# - one behavior declaration: workflow(...), workflow_graph(...), modes(...),
#   loop(...), map_each(...), or decision_rules(...) plus workflow(...)
#
# Static reviewer expectations:
# - frontmatter description states the capability and concrete activation trigger
#   before the contract body is loaded
# - frontmatter description is no broader than activate_when(...) and does not
#   contradict do_not_activate_when(...)
# - ids are stable snake_case strings and unique in their local scope
# - required inputs are consumed by a step, node, rule, or mode
# - required outputs are written by a step, node, rule, or mode
# - every branch reaches an output, stop condition, or user question
# - every loop has stop_when or max_iterations
# - every graph edge references existing nodes
# - declared resource paths exist or are explicitly generated by the skill
# - step actor values reference agent ids declared by agents(...)
# - every call_* marker includes enough natural-language instructions to perform
#   the interaction, understand the expected output, and handle failure


# ---------------------------------------------------------------------------
# Primitive contract value types
# ---------------------------------------------------------------------------

class Text: ...
class NaturalLanguage(Text): ...
class Path(Text): ...
class File(Path): ...
class Directory(Path): ...
class URL(Text): ...
class CallMarker(str): ...

# ---------------------------------------------------------------------------
# Opaque DSL element types
# ---------------------------------------------------------------------------

class InputSpec: ...
class OutputSpec: ...
class ScriptSpec: ...
class ReferenceSpec: ...
class AssetSpec: ...
class EnvSpec: ...
class AgentSpec: ...
class AgentPermissionsSpec: ...
class StepSpec: ...
class RuleSpec: ...
class NodeSpec: ...
class EdgeSpec: ...
class StopSpec: ...
class LoopSpec: ...
class MapSpec: ...
class ModeSpec: ...
class ExampleSpec: ...


# ---------------------------------------------------------------------------
# Shared literals
# ---------------------------------------------------------------------------

Match: TypeAlias = Literal["any", "all"]
ReadStrategy: TypeAlias = Literal["on_demand", "always", "never"]
NetworkPolicy: TypeAlias = Literal["unknown", "not_required", "optional", "required"]
FilesystemPolicy: TypeAlias = Literal["workspace", "read_only", "anywhere_with_user_request"]
JoinPolicy: TypeAlias = Literal["all", "any", "quorum", "available_only"]
FailurePolicy: TypeAlias = Literal[
    "stop_on_failure",
    "continue_and_record",
    "skip_failed_item",
    "ask_user",
]
SkillCallMode: TypeAlias = Literal["compose", "consult", "delegate", "handoff"]
AgentContext: TypeAlias = Literal["fork"] | str | None
AgentEffort: TypeAlias = Literal["low", "medium", "high"]
AgentFilesystemPolicy: TypeAlias = Literal["none", "read_only", "workspace_write"]


# ---------------------------------------------------------------------------
# Top-level declarations
# ---------------------------------------------------------------------------

def skill(
    *,
    name: str,
    purpose: str,
) -> None:
    """Required exactly once. Declares the skill identity and reusable capability."""
    ...


# ---------------------------------------------------------------------------
# Activation
# ---------------------------------------------------------------------------

def activate_when(
    conditions: list[str],
    *,
    match: Match = "any",
) -> None:
    """Positive trigger rules. Conditions should name concrete intents or contexts."""
    ...


def do_not_activate_when(
    conditions: list[str],
) -> None:
    """Negative trigger boundaries. These override activate_when when both match."""
    ...


# ---------------------------------------------------------------------------
# Inputs and outputs
# ---------------------------------------------------------------------------

def inputs(
    *,
    required: list[str | InputSpec],
    optional: list[str | InputSpec] | None = None,
    ask_when_missing: bool = True,
) -> None:
    """Declares inputs the agent must identify before executing the skill. ask_when_missing is a formal user-input gate."""
    ...


def input(
    name: str,
    *,
    type: object = Text,
    description: str | None = None,
    default: object | None = None,
    examples: list[object] | None = None,
    required: bool = True,
    required_when: str | None = None,
) -> InputSpec:
    """Declares one agent-facing input. required_when makes a required=False input conditionally mandatory."""
    ...


def outputs(
    *,
    required: list[str | OutputSpec],
    optional: list[str | OutputSpec] | None = None,
) -> None:
    """Declares observable results the skill must produce."""
    ...


def output(
    name: str,
    *,
    type: object = Text,
    description: str | None = None,
    format: str | None = None,
    template: str | None = None,
    required_sections: list[str] | None = None,
    success_criteria: list[str] | None = None,
) -> OutputSpec:
    """Declares one output and how a reviewer can recognize success."""
    ...


# ---------------------------------------------------------------------------
# Resources and environment
# ---------------------------------------------------------------------------

def resources(
    *,
    scripts: list[ScriptSpec] | None = None,
    references: list[ReferenceSpec] | None = None,
    assets: list[AssetSpec] | None = None,
) -> None:
    """Declares bundled resources the agent may load or use."""
    ...


def script(
    path: str,
    *,
    when: str | None = None,
    interface: str | None = None,
    run_help_first: bool = False,
    black_box: bool = True,
    requires: list[str] | None = None,
    outputs: list[str] | None = None,
) -> ScriptSpec:
    """Declares an agent-callable script interface, not its implementation details."""
    ...


def reference(
    path: str,
    *,
    when: str | None = None,
    read_strategy: ReadStrategy = "on_demand",
) -> ReferenceSpec:
    """Declares a reference file and when the agent should read it."""
    ...


def asset(
    path: str,
    *,
    when: str | None = None,
) -> AssetSpec:
    """Declares a static asset used by skill outputs."""
    ...


def environment(
    *,
    variables: list[EnvSpec] | None = None,
    commands: list[str] | None = None,
    dependencies: list[str] | None = None,
    network: NetworkPolicy = "unknown",
    filesystem: FilesystemPolicy = "workspace",
) -> None:
    """Declares environment assumptions that affect execution."""
    ...


def env(
    name: str,
    *,
    when: str | None = None,
    default: str | None = None,
    required: bool = False,
    secret: bool = False,
) -> EnvSpec:
    """Declares one environment variable and when it matters. Mark secrets explicitly."""
    ...


# ---------------------------------------------------------------------------
# Multi-agent declarations
# ---------------------------------------------------------------------------

def agents(
    items: list[AgentSpec],
) -> None:
    """Declares stable agent roles used by this skill. Use call_subagent(...) only where an actual delegation occurs."""
    ...


def agent(
    id: str,
    *,
    purpose: str,
    responsibilities: list[str],
    inputs: list[str | InputSpec] | None = None,
    outputs: list[str | OutputSpec] | None = None,
    context: AgentContext = None,
    effort: AgentEffort | None = None,
    permissions: AgentPermissionsSpec | None = None,
    forbidden: list[str] | None = None,
) -> AgentSpec:
    """Declares one reusable agent role, its context boundary, permissions, and owned outputs."""
    ...


def agent_permissions(
    *,
    filesystem: AgentFilesystemPolicy = "read_only",
    tools: list[str] | None = None,
    can_edit: bool = False,
    can_commit: bool = False,
    can_contact_external: bool = False,
) -> AgentPermissionsSpec:
    """Declares the side-effect boundary for one agent role."""
    ...


# ---------------------------------------------------------------------------
# Embedded call markers
# ---------------------------------------------------------------------------

def call_script(
    target: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a skill-bundled script call inside natural language. target is a path relative to the skill directory."""
    ...


def call_tool(
    name: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a normal agent tool or CLI call inside natural language."""
    ...


def call_mcp(
    server: str,
    tool: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks an MCP tool call inside natural language. server and tool must both be named."""
    ...


def call_skill(
    name: str,
    how: str,
    *,
    mode: SkillCallMode | None = None,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks use of another skill inside natural language. mode clarifies whether this is composition, consultation, delegation, or handoff."""
    ...


def call_subagent(
    role: str,
    task: str,
    how: str,
    *,
    context: AgentContext = None,
    effort: AgentEffort | None = None,
    result_path: str | None = None,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a subagent delegation inside natural language. context=None leaves the context boundary unspecified; context='fork' explicitly inherits current context; a string describes bounded context to pass."""
    ...


def call_human(
    request: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a user question, confirmation, consent request, or human decision point inside natural language. Use structured fields for formal gates."""
    ...


# ---------------------------------------------------------------------------
# Linear workflow
# ---------------------------------------------------------------------------

def workflow(
    steps: list[StepSpec],
    *,
    name: str | None = None,
) -> None:
    """Declares a linear or mostly linear behavior path."""
    ...


def step(
    id: str,
    action: str,
    *,
    actor: str | None = None,
    purpose: str | None = None,
    reads: list[str] | None = None,
    writes: list[str] | None = None,
    when: str | None = None,
    ask_user: str | None = None,
) -> StepSpec:
    """One agent action. id must be stable and unique inside its workflow. ask_user declares a formal user-input gate for this step."""
    ...


# ---------------------------------------------------------------------------
# Decision rules
# ---------------------------------------------------------------------------

def decision_rules(
    rules: list[RuleSpec],
) -> None:
    """Declares flat conditional rules and lightweight preferences."""
    ...


def when(
    condition: str,
    *,
    then: str,
    else_: str | None = None,
) -> RuleSpec:
    """Declares a condition and the behavior it selects."""
    ...


# ---------------------------------------------------------------------------
# Graph workflow
# ---------------------------------------------------------------------------

def workflow_graph(
    *,
    name: str,
    entry: str,
    nodes: list[NodeSpec],
    edges: list[EdgeSpec],
    exits: list[str] | None = None,
    termination: list[StopSpec] | None = None,
    state: dict[str, str] | None = None,
    invariants: list[str] | None = None,
) -> None:
    """Use only when workflow() cannot represent branches, joins, or back edges."""
    ...


def node(
    id: str,
    *,
    action: str,
    purpose: str | None = None,
    reads: list[str] | None = None,
    writes: list[str] | None = None,
) -> NodeSpec:
    """Declares a graph node. Put tool, script, MCP, skill, subagent, or human calls inside action f-strings."""
    ...


def edge(
    from_: str | list[str],
    to: str | list[str],
    *,
    when: str | None = None,
    parallel: bool = False,
    join: JoinPolicy | None = None,
    label: str | None = None,
) -> EdgeSpec:
    """Declares graph transitions. All referenced nodes must exist."""
    ...


def stop_when(
    condition: str,
    *,
    reason: str | None = None,
) -> StopSpec:
    """Declares a termination condition."""
    ...


# ---------------------------------------------------------------------------
# Iteration and collection processing
# ---------------------------------------------------------------------------

def loop(
    *,
    name: str,
    body: list[str | StepSpec] | list[StepSpec],
    continue_when: list[str] | None = None,
    stop_when: list[str] | None = None,
    max_iterations: int | None = None,
    invariant: list[str] | None = None,
    writes: list[str] | None = None,
) -> LoopSpec:
    """Declares iteration. Every loop must have stop_when or max_iterations."""
    ...


def map_each(
    *,
    name: str,
    over: str,
    item: str,
    do: list[StepSpec],
    collect_as: str,
    failure_policy: FailurePolicy = "stop_on_failure",
    parallel: bool = False,
) -> MapSpec:
    """Runs the same step list over each item in a collection. failure_policy='ask_user' is a formal per-item failure gate."""
    ...


# ---------------------------------------------------------------------------
# Modes
# ---------------------------------------------------------------------------

def modes(
    modes: list[ModeSpec],
    *,
    default: str | None = None,
    selection: str | None = None,
) -> None:
    """Declares top-level operating modes for one skill."""
    ...


def mode(
    name: str,
    *,
    trigger: str,
    workflow: str | list[StepSpec],
    inputs: list[InputSpec] | None = None,
    outputs: list[OutputSpec] | None = None,
    description: str | None = None,
    prerequisites: list[str] | None = None,
    forbidden: list[str] | None = None,
) -> ModeSpec:
    """Declares one operating mode, the trigger that selects it, and any mode-specific interface."""
    ...


# ---------------------------------------------------------------------------
# Quality and examples
# ---------------------------------------------------------------------------

def quality_bar(
    *,
    must: list[str],
    should: list[str] | None = None,
    must_not: list[str] | None = None,
) -> None:
    """Declares observable quality criteria for the final result."""
    ...


def examples(
    items: list[ExampleSpec],
) -> None:
    """Declares behavioral examples for humans, agents, and reviewers."""
    ...


def example(
    *,
    user: str,
    expected_behavior: str,
    input_files: list[str] | None = None,
    output: str | None = None,
) -> ExampleSpec:
    """One user prompt and expected skill behavior."""
    ...
