from __future__ import annotations

from typing import Literal, TypeAlias

# Skill Contract DSL v0.1
#
# This file is the normative API spec for Python Skill Contract blocks.
# A contract block should be written as disciplined Python-shaped code that imports:
#
#     from skill_contract import *
#
# The DSL describes agent behavior. It is not a general-purpose programming
# interface, and agents must not invent functions that are absent from this
# file.
#
# Natural language is allowed inside string and f-string fields. Use call_*()
# markers inside those strings to annotate script, tool, MCP, skill, or human
# interactions.
# These markers do not execute anything; they make the intended call auditable.
# They do not replace structured control-flow gates such as ask_when_missing,
# ask_user, ask_when_uncertain, human_input, failure_policy="ask_user",
# require_user_approval, approval_required, or validation(on_failure="ask_user").
#
# Minimal complete contract:
# - exactly one skill(...)
# - at least one activate_when(...)
# - do_not_activate_when(...) unless the skill has no meaningful neighbor
# - inputs(...) and outputs(...)
# - one behavior declaration: workflow(...), workflow_graph(...), state_machine(...),
#   modes(...), loop(...), map_each(...), or decision_rules(...) plus workflow(...)
#
# Static reviewer expectations:
# - frontmatter description states the capability and concrete activation trigger
#   before the contract body is loaded
# - frontmatter description is no broader than activate_when(...) and does not
#   contradict do_not_activate_when(...)
# - ids are stable snake_case strings and unique in their local scope
# - required inputs are consumed by a step, node, rule, or mode
# - required outputs are produced by a step, node, rule, or mode
# - every branch reaches an output, stop condition, or user question
# - every loop has stop_when or max_iterations
# - every graph edge references existing nodes
# - declared resource paths exist or are explicitly generated by the skill
# - every call_* marker includes enough natural-language instructions to perform
#   the interaction, understand the expected output, and handle failure


# ---------------------------------------------------------------------------
# Primitive contract value types
# ---------------------------------------------------------------------------

class Text: ...
class NaturalLanguage(Text): ...
class Path(Text): ...
class File(Path): ...
class Directory(Path): ...
class URL(Text): ...
class Command(Text): ...
class Tool(Text): ...
class Script(Path): ...
class Reference(Path): ...
class Asset(Path): ...
class CallMarker(str): ...

JSONScalar: TypeAlias = str | int | float | bool | None
JSONValue: TypeAlias = JSONScalar | list["JSONValue"] | dict[str, "JSONValue"]


# ---------------------------------------------------------------------------
# Opaque DSL element types
# ---------------------------------------------------------------------------

class InputSpec: ...
class OutputSpec: ...
class ScriptSpec: ...
class ReferenceSpec: ...
class AssetSpec: ...
class EnvSpec: ...
class StepSpec: ...
class DecisionSpec: ...
class RuleSpec: ...
class PreferenceSpec: ...
class ChoiceSpec: ...
class NodeSpec: ...
class EdgeSpec: ...
class StopSpec: ...
class LoopSpec: ...
class MapSpec: ...
class ReduceSpec: ...
class RetrySpec: ...
class StateSpec: ...
class TransitionSpec: ...
class ModeSpec: ...
class CheckSpec: ...
class ExampleSpec: ...
class LevelSpec: ...


# ---------------------------------------------------------------------------
# Shared literals
# ---------------------------------------------------------------------------

Match: TypeAlias = Literal["any", "all"]
ActivationStrength: TypeAlias = Literal[
    "weak",
    "normal",
    "strong",
    "always_when_matched",
]
ReadStrategy: TypeAlias = Literal["on_demand", "always", "never"]
NetworkPolicy: TypeAlias = Literal["unknown", "not_required", "optional", "required"]
FilesystemPolicy: TypeAlias = Literal["workspace", "read_only", "anywhere_with_user_request"]
JoinPolicy: TypeAlias = Literal["all", "any", "quorum", "available_only"]
FailurePolicy: TypeAlias = Literal[
    "stop_on_failure",
    "continue_and_record",
    "skip_failed_item",
    "ask_user",
]
FallbackApproval: TypeAlias = Literal["always", "when_destructive", "never"]
SeverityName: TypeAlias = Literal["critical", "major", "minor", "info"]
SkillCallMode: TypeAlias = Literal["compose", "consult", "delegate", "handoff"]
SubagentContext: TypeAlias = Literal["fork"] | str
SubagentEffort: TypeAlias = Literal["low", "medium", "high"]


# ---------------------------------------------------------------------------
# Top-level declarations
# ---------------------------------------------------------------------------

def skill(
    *,
    name: str,
    purpose: str,
    summary: str | None = None,
    version: str | None = None,
    owner: str | None = None,
    short_description: str | None = None,
    tags: list[str] | None = None,
    compatibility: list[str] | None = None,
    license: str | None = None,
    experimental: bool = False,
    custom: dict[str, JSONValue] | None = None,
) -> None:
    """Required exactly once. Declares the skill identity, reusable capability, and optional catalog metadata."""
    ...


# ---------------------------------------------------------------------------
# Activation
# ---------------------------------------------------------------------------

def activate_when(
    conditions: list[str],
    *,
    match: Match = "any",
    strength: ActivationStrength = "normal",
) -> None:
    """Positive trigger rules. Conditions should name concrete intents or contexts."""
    ...


def do_not_activate_when(
    conditions: list[str],
    *,
    priority: Literal["higher_than_activate_when"] = "higher_than_activate_when",
) -> None:
    """Negative trigger boundaries. These override activate_when when both match."""
    ...


# ---------------------------------------------------------------------------
# Inputs and outputs
# ---------------------------------------------------------------------------

def inputs(
    *,
    required: list[str | InputSpec],
    optional: list[str | InputSpec] | None = None,
    ask_when_missing: bool = True,
) -> None:
    """Declares inputs the agent must identify before executing the skill. ask_when_missing is a formal user-input gate."""
    ...


def input(
    name: str,
    *,
    type: object = Text,
    description: str | None = None,
    default: object | None = None,
    examples: list[object] | None = None,
    required: bool = True,
    required_when: str | None = None,
) -> InputSpec:
    """Declares one agent-facing input. required_when makes a required=False input conditionally mandatory."""
    ...


def outputs(
    *,
    required: list[str | OutputSpec],
    optional: list[str | OutputSpec] | None = None,
) -> None:
    """Declares observable results the skill must produce."""
    ...


def output(
    name: str,
    *,
    type: object = Text,
    description: str | None = None,
    format: str | None = None,
    template: str | None = None,
    required_sections: list[str] | None = None,
    success_criteria: list[str] | None = None,
) -> OutputSpec:
    """Declares one output and how a reviewer can recognize success."""
    ...


# ---------------------------------------------------------------------------
# Resources and environment
# ---------------------------------------------------------------------------

def resources(
    *,
    scripts: list[ScriptSpec] | None = None,
    references: list[ReferenceSpec] | None = None,
    assets: list[AssetSpec] | None = None,
) -> None:
    """Declares bundled resources the agent may load or use."""
    ...


def script(
    path: str,
    *,
    purpose: str | None = None,
    when: str | None = None,
    interface: str | None = None,
    run_help_first: bool = False,
    black_box: bool = True,
    requires: list[str] | None = None,
    outputs: list[str] | None = None,
) -> ScriptSpec:
    """Declares an agent-callable script interface, not its implementation details."""
    ...


def reference(
    path: str,
    *,
    purpose: str | None = None,
    when: str | None = None,
    read_strategy: ReadStrategy = "on_demand",
    grep_patterns: list[str] | None = None,
) -> ReferenceSpec:
    """Declares a reference file and when the agent should read it."""
    ...


def asset(
    path: str,
    *,
    purpose: str | None = None,
    when: str | None = None,
    copy_policy: Literal["copy_when_needed", "reference_only"] = "copy_when_needed",
) -> AssetSpec:
    """Declares a static asset used by skill outputs."""
    ...


def environment(
    *,
    variables: list[EnvSpec] | None = None,
    commands: list[str] | None = None,
    dependencies: list[str] | None = None,
    network: NetworkPolicy = "unknown",
    filesystem: FilesystemPolicy = "workspace",
) -> None:
    """Declares environment assumptions that affect execution."""
    ...


def env(
    name: str,
    *,
    default: str | None = None,
    required: bool = False,
    secret: bool = False,
    purpose: str | None = None,
) -> EnvSpec:
    """Declares one environment variable. Mark secrets explicitly."""
    ...


# ---------------------------------------------------------------------------
# Embedded call markers
# ---------------------------------------------------------------------------

def call_script(
    target: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a skill-bundled script call inside natural language. target is a path relative to the skill directory."""
    ...


def call_tool(
    name: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a normal agent tool or CLI call inside natural language."""
    ...


def call_mcp(
    server: str,
    tool: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks an MCP tool call inside natural language. server and tool must both be named."""
    ...


def call_skill(
    name: str,
    how: str,
    *,
    mode: SkillCallMode | None = None,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks use of another skill inside natural language. mode clarifies whether this is composition, consultation, delegation, or handoff."""
    ...


def call_subagent(
    role: str,
    task: str,
    how: str,
    *,
    context: SubagentContext = "fork",
    effort: SubagentEffort | None = None,
    result_path: str | None = None,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a subagent delegation inside natural language. context='fork' inherits current context; a string describes isolated context to pass."""
    ...


def call_human(
    request: str,
    how: str,
    *,
    expect: str | None = None,
    on_failure: str | None = None,
) -> CallMarker:
    """Marks a user question, confirmation, consent request, or human decision point inside natural language. Use structured fields for formal gates."""
    ...


# ---------------------------------------------------------------------------
# Linear workflow
# ---------------------------------------------------------------------------

def workflow(
    steps: list[StepSpec],
    *,
    name: str | None = None,
) -> None:
    """Declares a linear or mostly linear behavior path."""
    ...


def step(
    id: str,
    action: str,
    *,
    purpose: str | None = None,
    reads: list[str] | None = None,
    writes: list[str] | None = None,
    requires: list[str] | None = None,
    produces: list[str] | None = None,
    when: str | None = None,
    ask_user: str | None = None,
) -> StepSpec:
    """One agent action. id must be stable and unique inside its workflow. ask_user declares a formal user-input gate for this step."""
    ...


# ---------------------------------------------------------------------------
# Decisions and rules
# ---------------------------------------------------------------------------

def decision(
    id: str,
    question: str,
    *,
    branches: dict[str, str],
    default: str | None = None,
    ask_when_uncertain: bool = False,
) -> DecisionSpec:
    """Declares one branch point. ask_when_uncertain declares a formal user-input gate when branch selection is ambiguous."""
    ...


def decision_rules(
    rules: list[RuleSpec | PreferenceSpec | ChoiceSpec],
) -> None:
    """Declares flat conditional rules and preferences."""
    ...


def when(
    condition: str,
    *,
    then: str,
    else_: str | None = None,
) -> RuleSpec:
    """Declares a condition and the behavior it selects."""
    ...


def prefer(
    option: str,
    *,
    over: str,
    reason: str | None = None,
) -> PreferenceSpec:
    """Declares a default preference and why it is safer or more reliable."""
    ...


def choose(
    *,
    from_: list[str],
    by: str,
    default: str | None = None,
) -> ChoiceSpec:
    """Declares how to choose among named options."""
    ...


# ---------------------------------------------------------------------------
# Graph workflow
# ---------------------------------------------------------------------------

def workflow_graph(
    *,
    name: str,
    entry: str,
    nodes: list[NodeSpec],
    edges: list[EdgeSpec],
    exits: list[str] | None = None,
    termination: list[StopSpec] | None = None,
    state: dict[str, str] | None = None,
    invariants: list[str] | None = None,
) -> None:
    """Use only when workflow() cannot represent branches, joins, or back edges."""
    ...


def node(
    id: str,
    *,
    action: str,
    purpose: str | None = None,
    reads: list[str] | None = None,
    writes: list[str] | None = None,
    requires: list[str] | None = None,
    produces: list[str] | None = None,
    tool: str | None = None,
    script: str | None = None,
    human_input: str | None = None,
    retry: RetrySpec | None = None,
) -> NodeSpec:
    """Declares a graph node. human_input declares a formal user-input gate for this node."""
    ...


def edge(
    from_: str | list[str],
    to: str | list[str],
    *,
    when: str | None = None,
    parallel: bool = False,
    join: JoinPolicy | None = None,
    label: str | None = None,
) -> EdgeSpec:
    """Declares graph transitions. All referenced nodes must exist."""
    ...


def stop_when(
    condition: str,
    *,
    reason: str | None = None,
) -> StopSpec:
    """Declares a termination condition."""
    ...


# ---------------------------------------------------------------------------
# Iteration and collection processing
# ---------------------------------------------------------------------------

def loop(
    *,
    name: str,
    body: list[str | StepSpec] | list[StepSpec],
    continue_when: list[str] | None = None,
    stop_when: list[str] | None = None,
    max_iterations: int | None = None,
    invariant: list[str] | None = None,
    writes: list[str] | None = None,
) -> LoopSpec:
    """Declares iteration. Every loop must have stop_when or max_iterations."""
    ...


def map_each(
    *,
    name: str,
    over: str,
    item: str,
    do: list[StepSpec],
    collect_as: str,
    failure_policy: FailurePolicy = "stop_on_failure",
    parallel: bool = False,
) -> MapSpec:
    """Runs the same step list over each item in a collection. failure_policy='ask_user' is a formal per-item failure gate."""
    ...


def reduce(
    *,
    name: str,
    over: str,
    into: str,
    do: str,
) -> ReduceSpec:
    """Aggregates mapped results into one named state value."""
    ...


def retry(
    *,
    max_attempts: int,
    when: list[str],
    backoff: str | None = None,
    before_retry: str | None = None,
    after_exhausted: str | None = None,
) -> RetrySpec:
    """Declares retry behavior for a step or node."""
    ...


# ---------------------------------------------------------------------------
# State machines and modes
# ---------------------------------------------------------------------------

def state_machine(
    *,
    name: str,
    initial: str,
    states: list[StateSpec],
    transitions: list[TransitionSpec],
    stop_states: list[str],
    invariants: list[str] | None = None,
) -> None:
    """Use for durable human review, approval, or lifecycle states."""
    ...


def state(
    name: str,
    *,
    description: str | None = None,
    entry_action: str | None = None,
    exit_condition: str | None = None,
) -> StateSpec:
    """Declares one state. State names must be unique in a state_machine."""
    ...


def transition(
    from_: str,
    to: str,
    *,
    when: str | None = None,
    after: str | None = None,
    guard: str | None = None,
) -> TransitionSpec:
    """Declares a state transition. Referenced states must exist."""
    ...


def modes(
    modes: list[ModeSpec],
    *,
    default: str | None = None,
    selection: str | None = None,
) -> None:
    """Declares top-level operating modes for one skill."""
    ...


def mode(
    name: str,
    *,
    trigger: str,
    workflow: str | list[StepSpec],
    description: str | None = None,
    prerequisites: list[str] | None = None,
    forbidden: list[str] | None = None,
) -> ModeSpec:
    """Declares one operating mode and the trigger that selects it."""
    ...


# ---------------------------------------------------------------------------
# Failure, fallback, and safety
# ---------------------------------------------------------------------------

def failure_modes(
    modes: list[RuleSpec],
) -> None:
    """Declares common failures and required agent responses."""
    ...


def fallback_strategy(
    rules: list[RuleSpec],
    *,
    require_user_approval: bool | FallbackApproval = False,
) -> None:
    """Declares fallback behavior after the preferred path is unavailable. require_user_approval is a formal fallback gate."""
    ...


def safety_policy(
    *,
    must: list[str] | None = None,
    must_not: list[str] | None = None,
    approval_required: list[str] | None = None,
) -> None:
    """Declares safety constraints that govern all workflow paths. approval_required lists formal approval gates."""
    ...


# ---------------------------------------------------------------------------
# Quality, validation, and examples
# ---------------------------------------------------------------------------

def quality_bar(
    *,
    must: list[str],
    should: list[str] | None = None,
    must_not: list[str] | None = None,
) -> None:
    """Declares observable quality criteria for the final result."""
    ...


def validation(
    checks: list[CheckSpec],
    *,
    on_failure: Literal["report", "repair", "ask_user", "stop"] = "report",
) -> None:
    """Declares validation actions or checks. on_failure='ask_user' is a formal validation-failure gate."""
    ...


def check(
    id: str,
    description: str,
    *,
    command: str | None = None,
    expected: str | None = None,
) -> CheckSpec:
    """Declares one validation check. command is optional."""
    ...


def examples(
    items: list[ExampleSpec],
) -> None:
    """Declares behavioral examples for humans, agents, and reviewers."""
    ...


def example(
    *,
    user: str,
    expected_behavior: str,
    input_files: list[str] | None = None,
    output: str | None = None,
) -> ExampleSpec:
    """One user prompt and expected skill behavior."""
    ...


# ---------------------------------------------------------------------------
# Output and review helpers
# ---------------------------------------------------------------------------

def severity_levels(
    levels: list[LevelSpec],
) -> None:
    """Declares severity vocabulary for reviews or reports."""
    ...


def level(
    name: SeverityName | str,
    meaning: str,
) -> LevelSpec:
    """Declares one severity level."""
    ...


def review_dimensions(
    dimensions: list[str],
) -> None:
    """Declares dimensions a reviewer should inspect."""
    ...
